blank_issues_enabled: true
contact_links:
  - name: Discord
    url: https://discord.gg/sAX6PXZ9
    about: Join our Discord for questions and discussions
  - name: QQ Group (481923584)
    url: https://qm.qq.com/q/BONa5LXQ0U
    about: Join our QQ group for Chinese-speaking community
